"""Git hook installer and runner for model-agnostic and harness-agnostic enforcement."""

from __future__ import annotations
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional

from aos.enforcer import enforce_all

PRE_COMMIT_SCRIPT = """#!/usr/bin/env sh
# AOS Git Pre-Commit Invariant Guard
# Automatically generated by aos hook install

python -m aos hook run
"""


def install_git_hook(root_dir: Path | str = ".") -> Path:
    """Install the AOS pre-commit hook in .git/hooks/pre-commit."""
    root = Path(root_dir)
    git_dir = root / ".git"
    if not git_dir.is_dir():
        raise RuntimeError(f"No .git directory found at {root}")

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_file = hooks_dir / "pre-commit"
    hook_file.write_text(PRE_COMMIT_SCRIPT, encoding="utf-8")

    # Make executable on POSIX environments
    try:
        current_mode = hook_file.stat().st_mode
        hook_file.chmod(current_mode | 0o755)
    except Exception:
        pass

    return hook_file


def uninstall_git_hook(root_dir: Path | str = ".") -> bool:
    """Remove the AOS pre-commit hook if installed."""
    root = Path(root_dir)
    hook_file = root / ".git" / "hooks" / "pre-commit"
    if hook_file.is_file():
        hook_file.unlink()
        return True
    return False


def get_staged_files(root_dir: Path | str = ".") -> list[str]:
    """Retrieve list of staged files from git index."""
    try:
        res = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            cwd=str(root_dir),
            capture_output=True,
            text=True,
            check=True,
        )
        return [f.strip() for f in res.stdout.splitlines() if f.strip()]
    except Exception:
        return []


def run_pre_commit_check(root_dir: Path | str = ".") -> int:
    """Execute pre-commit invariant validation on staged files."""
    staged = get_staged_files(root_dir)
    if not staged:
        return 0

    violations = enforce_all(staged, root_dir=root_dir)
    reject_violations = [v for v in violations if v.enforcement == "reject_diff"]

    if reject_violations:
        try:
            from aos.blackboard import post_event
            from aos.harness import sync_harnesses
            for v in reject_violations:
                post_event(
                    {
                        "type": "PRE_COMMIT_BLOCKED",
                        "sender": "git-pre-commit-barrier",
                        "payload": {
                            "rule_id": v.rule_id,
                            "file_path": v.file_path,
                            "line_number": v.line_number,
                            "message": v.message,
                            "statement": v.statement,
                        },
                    },
                    root_dir=root_dir,
                )
            sync_harnesses(root_dir=root_dir)
        except Exception:
            pass

        print("=" * 70, file=sys.stderr)
        print("AOS COMMIT REJECTED: Invariant violations detected in staged files:", file=sys.stderr)
        print("=" * 70, file=sys.stderr)
        for v in reject_violations:
            loc = f":{v.line_number}" if v.line_number else ""
            print(f"[{v.rule_id}] {v.file_path}{loc}", file=sys.stderr)
            print(f"  {v.message}", file=sys.stderr)
        print("=" * 70, file=sys.stderr)
        print("AOS self-improvement loop: Failure recorded and agent prompts re-synced.", file=sys.stderr)
        print("Run 'aos enforce --fix <file>' to attempt automated remediation.", file=sys.stderr)
        return 1

    return 0
